services:
  llm_pt25_service:
    build:
      context: ./
      dockerfile: pytorch25.Dockerfile
    image: mvp-pt:2.5.1
    container_name: mvp-pt25
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${CODE}
        target: ${CODE}
      # - type: bind
      #   source: ${CONDA}
      #   target: ${CONDA}
      - type: bind
        source: ${DATASET}
        target: ${DATASET}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    security_opt:
      - apparmor:unconfined
    ipc: host
    
    stdin_open: true 
    tty: true

    # Forubuntu
    # runtime: nvidia
    # Only for wsl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

